### ISSUE TITLE
Revise Game Concept

### ISSUE THREAD

**Issue by DarioLohmuller** [mathieuheer/roestigraben#3]
Should we revise the game concept?
Or what is the plan regarding this matter?

**Comment by mathieuheer** [comment]
Do you mean the original game concept of the swiss apocalypse or the concept right now with the islands?

**Comment by DarioLohmuller** [comment]
The original concept. I don't think it does really fit anymore. But I also don't know if it is relevant for the end-product.

**Comment by DarioLohmuller** [comment]
Not necessary adapting the game conpcent.
